GET http://localhost:3000/greet

###

GET http://localhost:8765/customers
content-type: application/json

###

# Not in DB
GET http://localhost:3000/customers/1001

###

GET http://localhost:3000/customers/2001

###

GET http://localhost:3000/customers?status=active

###

GET http://localhost:3000/customers?status=inactive

###

GET http://localhost:3000/customers?status=13edrws

###

POST http://localhost:3000/customers/2001/account
content-type: application/json

{
    "account_type": "savinsg",
    "amount": 5000.2
}

###

POST http://localhost:3000/customers/2002/transaction/95471
content-type: application/json

{
    "transaction_type": "withdrawal",
    "amount": 50.2
}
{customer_id:[0-9]+}/transaction/{account_id:[0-9]+}