GET http://localhost:3000/greet

###

GET http://localhost:3000/customers
content-type: application/json

###

# Not in DB
GET http://localhost:3000/customers/1002

###

GET http://localhost:3000/customers/2005

###

GET http://localhost:3000/customers?status=active

###

GET http://localhost:3000/customers?status=inactive

###

GET http://localhost:3000/customers?status=13edrws