name: Go-Banking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./cmd/banking/main.go
      
    - name: Run cmd/banking/main.go
      run: timeout 5 go run ./cmd/banking/main.go || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

    # - name: Test
    #   run: go test -v ./...
