name: Go-Banking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  banking-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build server
      run: go build -v ./cmd/server/main.go
      
    - name: Run server
      run: timeout 5 go run ./cmd/server/main.go || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      env:
        BANKING_HOST: 0.0.0.0
        BANKING_PORT: 8765
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USER: root
        DB_PASS: codecamp
        DB_NAME: banking

    # - name: Test
    #   run: go test -v ./...
  
  banking-auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build server
      run: go build -v ./cmd/auth/main.go
      
    - name: Run server
      run: timeout 5 go run ./cmd/auth/main.go || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      env:
        AUTH_HOST: 0.0.0.0
        AUTH_PORT: 8181
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USER: root
        DB_PASS: codecamp
        DB_NAME: banking

    # - name: Test
    #   run: go test -v ./...
